spring:
  application:
    name: ecofarming

  profiles:
    active: local # 기본 프로파일 설정

  jpa:
    hibernate:
      ddl-auto: update # 기본값, 필요시 변경 가능

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jwt:
    secret: ${JWT_SECRET}

  redis:
    host: ${REDIS_HOST}
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 6000ms

webhook:
  mattermost:
    report:
      url: ${MM_REPORT_URL}
      priority: standard
    error:
      url: ${MM_ERROR_URL}
      priority: important

firebase:
  config: file:${FIREBASE_CONFIG_PATH}

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health, info
