spring:
  datasource:
    url: jdbc:mysql://j11a101.p.ssafy.io:3306/ecofarming
    username: root
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  redis:
    host: j11a101.p.ssafy.io
    port: 6379
    password: ${REDIS_PASSWORD}
    timeout: 6000ms

file:
  upload-dir: /home/ubuntu/uploads

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
