spring:
  security:
    oauth2:
      client:
        registration:
          google:
#            redirect-uri: "http://localhost:8083/api/login/oauth2/code/google"
            redirect-uri: "https://i11a707.p.ssafy.io/api/login/oauth2/code/google"
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email